"""added mls number

Revision ID: 010642ddb264
Revises: 705bca1760e2
Create Date: 2026-03-02 21:13:07.695465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010642ddb264'
down_revision: Union[str, None] = '705bca1760e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('listing_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'listing_id')
    # ### end Alembic commands ###
