"""Tour complete

Revision ID: 02049ff44600
Revises: 5accd1d3c095
Create Date: 2026-03-01 18:26:21.552460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02049ff44600'
down_revision: Union[str, None] = '5accd1d3c095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_tours', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.drop_column('property_tours', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_tours', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('property_tours', 'is_completed')
    # ### end Alembic commands ###
