"""Add plan_id and plan_tier to users

Revision ID: 02b055d0e3e2
Revises: 4d972b5c9240
Create Date: 2025-10-09 19:47:15.427330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b055d0e3e2'
down_revision: Union[str, None] = '4d972b5c9240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed foreign key constraint changes - SQLite doesn't support them
    op.add_column('users', sa.Column('plan_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan_tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan_tier')
    op.drop_column('users', 'plan_id')
    # ### end Alembic commands ###
