"""Add ResoFacts table and rename Property.zpid to listing_key

Revision ID: 062297980aa5
Revises: 74520f8dc278
Create Date: 2026-01-27 13:12:54.886991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database


# revision identifiers, used by Alembic.
revision: str = '062297980aa5'
down_revision: Union[str, None] = '74520f8dc278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reso_facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('architectural_style', sa.String(), nullable=True),
    sa.Column('construction_materials', sa.String(), nullable=True),
    sa.Column('roof_type', sa.String(), nullable=True),
    sa.Column('foundation_details', sa.String(), nullable=True),
    sa.Column('structure_type', sa.String(), nullable=True),
    sa.Column('levels', sa.String(), nullable=True),
    sa.Column('interior_features', sa.JSON(), nullable=True),
    sa.Column('exterior_features', sa.JSON(), nullable=True),
    sa.Column('flooring', sa.JSON(), nullable=True),
    sa.Column('appliances', sa.JSON(), nullable=True),
    sa.Column('fireplaces', sa.Integer(), nullable=True),
    sa.Column('fireplace_features', sa.JSON(), nullable=True),
    sa.Column('door_features', sa.JSON(), nullable=True),
    sa.Column('window_features', sa.JSON(), nullable=True),
    sa.Column('cooling', sa.JSON(), nullable=True),
    sa.Column('heating', sa.JSON(), nullable=True),
    sa.Column('water_source', sa.JSON(), nullable=True),
    sa.Column('sewer', sa.JSON(), nullable=True),
    sa.Column('electric', sa.JSON(), nullable=True),
    sa.Column('utilities', sa.JSON(), nullable=True),
    sa.Column('garage_spaces', sa.Float(), nullable=True),
    sa.Column('parking_features', sa.JSON(), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=True),
    sa.Column('association_fee', sa.Integer(), nullable=True),
    sa.Column('association_fee_frequency', sa.String(), nullable=True),
    sa.Column('association_amenities', sa.JSON(), nullable=True),
    sa.Column('association_fee_includes', sa.JSON(), nullable=True),
    sa.Column('has_association', sa.Boolean(), nullable=True),
    sa.Column('lot_features', sa.JSON(), nullable=True),
    sa.Column('topography', sa.String(), nullable=True),
    sa.Column('view', sa.JSON(), nullable=True),
    sa.Column('waterfront_features', sa.JSON(), nullable=True),
    sa.Column('has_waterfront_view', sa.Boolean(), nullable=True),
    sa.Column('has_view', sa.Boolean(), nullable=True),
    sa.Column('tax_annual_amount', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('modification_timestamp', app.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.TZDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', app.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.add_column('properties', sa.Column('listing_key', sa.String(), nullable=True))
    op.drop_index('ix_properties_zpid', table_name='properties')
    op.create_index(op.f('ix_properties_listing_key'), 'properties', ['listing_key'], unique=True)
    op.drop_column('properties', 'zpid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('zpid', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_properties_listing_key'), table_name='properties')
    op.create_index('ix_properties_zpid', 'properties', ['zpid'], unique=1)
    op.drop_column('properties', 'listing_key')
    op.drop_table('reso_facts')
    # ### end Alembic commands ###
