"""Added mls id unique

Revision ID: 0f248eb7f0b7
Revises: 555a3b496371
Create Date: 2026-02-20 23:01:09.941432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f248eb7f0b7'
down_revision: Union[str, None] = '555a3b496371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'brokerage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'mls_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_mls_id'), 'users', ['mls_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mls_id'), table_name='users')
    op.alter_column('users', 'mls_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'brokerage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
