"""add_comprehensive_property_details

Revision ID: 1475015cfe12
Revises: 26edcbf1c61d
Create Date: 2026-02-13 17:00:50.467935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1475015cfe12'
down_revision: Union[str, None] = '26edcbf1c61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_details', sa.Column('elementary_school', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('middle_or_junior_school', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('high_school', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('school_district_name', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('county', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('directions', sa.Text(), nullable=True))
    op.add_column('property_details', sa.Column('cross_street', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('walk_score', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('zoning', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('direction_faces', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('tax_assessment_amount', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('land_assessment_amount', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('improvement_assessment_amount', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('assessment_year', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('capital_contribution_fee', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('possession', sa.JSON(), nullable=True))
    op.add_column('property_details', sa.Column('cooling_fuel', sa.JSON(), nullable=True))
    op.add_column('property_details', sa.Column('heating_fuel', sa.JSON(), nullable=True))
    op.add_column('property_details', sa.Column('lot_size_acres', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('attached_garage_yn', sa.Boolean(), nullable=True))
    op.add_column('property_details', sa.Column('new_construction_yn', sa.Boolean(), nullable=True))
    op.add_column('property_details', sa.Column('senior_community_yn', sa.Boolean(), nullable=True))
    op.add_column('property_details', sa.Column('pets_allowed', sa.JSON(), nullable=True))
    op.add_column('property_details', sa.Column('original_list_price', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('days_on_market', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('cumulative_days_on_market', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('standard_status', sa.String(), nullable=True))
    op.add_column('property_details', sa.Column('stories', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('stories_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_details', 'stories_total')
    op.drop_column('property_details', 'stories')
    op.drop_column('property_details', 'standard_status')
    op.drop_column('property_details', 'cumulative_days_on_market')
    op.drop_column('property_details', 'days_on_market')
    op.drop_column('property_details', 'original_list_price')
    op.drop_column('property_details', 'pets_allowed')
    op.drop_column('property_details', 'senior_community_yn')
    op.drop_column('property_details', 'new_construction_yn')
    op.drop_column('property_details', 'attached_garage_yn')
    op.drop_column('property_details', 'lot_size_acres')
    op.drop_column('property_details', 'heating_fuel')
    op.drop_column('property_details', 'cooling_fuel')
    op.drop_column('property_details', 'possession')
    op.drop_column('property_details', 'capital_contribution_fee')
    op.drop_column('property_details', 'assessment_year')
    op.drop_column('property_details', 'improvement_assessment_amount')
    op.drop_column('property_details', 'land_assessment_amount')
    op.drop_column('property_details', 'tax_assessment_amount')
    op.drop_column('property_details', 'direction_faces')
    op.drop_column('property_details', 'zoning')
    op.drop_column('property_details', 'walk_score')
    op.drop_column('property_details', 'cross_street')
    op.drop_column('property_details', 'directions')
    op.drop_column('property_details', 'county')
    op.drop_column('property_details', 'school_district_name')
    op.drop_column('property_details', 'high_school')
    op.drop_column('property_details', 'middle_or_junior_school')
    op.drop_column('property_details', 'elementary_school')
    # ### end Alembic commands ###
