"""Remove old preferences JSON column

Revision ID: 16fae2c172bd
Revises: 23243cbdb43d
Create Date: 2025-08-24 21:50:30.416711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fae2c172bd'
down_revision: Union[str, None] = '23243cbdb43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
