"""Add cover_image_url to open_house_events

Revision ID: 17ba935740a8
Revises: 144c9a6a8e24
Create Date: 2025-08-25 12:34:02.470382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ba935740a8'
down_revision: Union[str, None] = '144c9a6a8e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_house_events', sa.Column('cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_house_events', 'cover_image_url')
    # ### end Alembic commands ###
