"""Add living_area to open_house_events

Revision ID: 1a8a112b8e54
Revises: fa7ff1cc3dd2
Create Date: 2025-11-20 03:11:31.437372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8a112b8e54'
down_revision: Union[str, None] = 'fa7ff1cc3dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_house_events', sa.Column('living_area', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_house_events', 'living_area')
    # ### end Alembic commands ###
