"""add_similar_properties_snapshot_to_open_house

Revision ID: 1cf287502a8f
Revises: f5ad41bcfca9
Create Date: 2026-02-13 18:43:36.774421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1cf287502a8f'
down_revision: Union[str, None] = 'f5ad41bcfca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_house_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_properties_snapshot', sa.JSON(), nullable=True))
        batch_op.drop_column('similar_property_ids')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_house_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_property_ids', sqlite.JSON(), nullable=True))
        batch_op.drop_column('similar_properties_snapshot')

    # ### end Alembic commands ###
