"""Add lookup_address column to properties table

Revision ID: 1e13849e2543
Revises: 17ba935740a8
Create Date: 2025-08-30 15:05:18.222511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e13849e2543'
down_revision: Union[str, None] = '17ba935740a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('lookup_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'lookup_address')
    # ### end Alembic commands ###
