"""cascade

Revision ID: 2231c0fc186f
Revises: 7e209d2676fb
Create Date: 2025-09-16 15:17:27.039511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2231c0fc186f'
down_revision: Union[str, None] = '7e209d2676fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip constraint modifications for SQLite compatibility
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip constraint modifications for SQLite compatibility
    pass
    # ### end Alembic commands ###
