"""Add added_at timestamp to collection_properties

Revision ID: 27af84211dee
Revises: b86c7aa8a61c
Create Date: 2025-10-21 21:21:59.266483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27af84211dee'
down_revision: Union[str, None] = 'b86c7aa8a61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the added_at column - skip foreign key changes for SQLite compatibility
    with op.batch_alter_table('collection_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_properties', schema=None) as batch_op:
        batch_op.drop_column('added_at')
    # ### end Alembic commands ###
