"""add_categorical_and_discovery_tables

Revision ID: 27e3940dfd06
Revises: 74476447af04
Create Date: 2026-05-13 15:30:05.551835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e3940dfd06'
down_revision: Union[str, None] = '74476447af04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_discover_preferences_latitude")
    op.execute("DROP INDEX IF EXISTS ix_discover_preferences_longitude")
    op.execute("DROP TABLE IF EXISTS discover_preferences")
    op.execute("DROP INDEX IF EXISTS idx_properties_full_address_trgm")
    op.create_index(op.f('ix_properties_full_address'), 'properties', ['full_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_full_address'), table_name='properties')
    op.create_index('idx_properties_full_address_trgm', 'properties', ['full_address'], unique=False, postgresql_using='gin')
    op.create_table('discover_preferences',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('landmark_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('miles', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('brokerages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('school_districts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='discover_preferences_pkey')
    )
    op.create_index('ix_discover_preferences_longitude', 'discover_preferences', ['longitude'], unique=False)
    op.create_index('ix_discover_preferences_latitude', 'discover_preferences', ['latitude'], unique=False)
    # ### end Alembic commands ###
