"""Add view tracking to property interactions

Revision ID: 2876c2022ee8
Revises: af3e07e53e9a
Create Date: 2025-11-17 17:35:52.052822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '2876c2022ee8'
down_revision: Union[str, None] = 'af3e07e53e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_interactions', sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('property_interactions', sa.Column('last_viewed_at', TZDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_interactions', 'last_viewed_at')
    op.drop_column('property_interactions', 'view_count')
    # ### end Alembic commands ###
