"""Add min_year_built and max_year_built to collection_preferences

Revision ID: 2ca0cb39fddd
Revises: 2876c2022ee8
Create Date: 2025-11-17 19:00:26.088985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca0cb39fddd'
down_revision: Union[str, None] = '2876c2022ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_preferences', sa.Column('min_year_built', sa.Integer(), nullable=True))
    op.add_column('collection_preferences', sa.Column('max_year_built', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_preferences', 'max_year_built')
    op.drop_column('collection_preferences', 'min_year_built')
    # ### end Alembic commands ###
