"""Updated the cities

Revision ID: 2d6c5473567d
Revises: fbd80bcbd06d
Create Date: 2025-09-12 01:52:12.066801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6c5473567d'
down_revision: Union[str, None] = 'fbd80bcbd06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_preferences', sa.Column('cities', sa.JSON(), nullable=True))
    op.add_column('collection_preferences', sa.Column('townships', sa.JSON(), nullable=True))
    op.drop_column('collection_preferences', 'township')
    op.drop_column('collection_preferences', 'city')
    op.drop_column('open_house_events', 'lot_size')
    op.drop_column('open_house_events', 'start_time')
    op.drop_column('open_house_events', 'year_built')
    op.drop_column('open_house_events', 'end_time')
    op.drop_column('open_house_events', 'living_area')
    op.drop_column('open_house_events', 'image_src')
    op.drop_column('open_house_visitors', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('open_house_visitors', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('open_house_events', sa.Column('image_src', sa.VARCHAR(), nullable=True))
    op.add_column('open_house_events', sa.Column('living_area', sa.INTEGER(), nullable=True))
    op.add_column('open_house_events', sa.Column('end_time', sa.DATETIME(), nullable=False))
    op.add_column('open_house_events', sa.Column('year_built', sa.INTEGER(), nullable=True))
    op.add_column('open_house_events', sa.Column('start_time', sa.DATETIME(), nullable=False))
    op.add_column('open_house_events', sa.Column('lot_size', sa.INTEGER(), nullable=True))
    op.add_column('collection_preferences', sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('collection_preferences', sa.Column('township', sa.VARCHAR(), nullable=True))
    op.drop_column('collection_preferences', 'townships')
    op.drop_column('collection_preferences', 'cities')
    # ### end Alembic commands ###
