"""Add blacklisted_emails table

Revision ID: 2eed9048440b
Revises: 635d0b21ac5b
Create Date: 2026-03-12 18:52:35.738836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eed9048440b'
down_revision: Union[str, None] = '635d0b21ac5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
