"""add days_on_zillow column to properties table

Revision ID: 3158e8c609d8
Revises: bc42630995d7
Create Date: 2025-11-16 05:17:59.262800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3158e8c609d8'
down_revision: Union[str, None] = 'bc42630995d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('days_on_zillow', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'days_on_zillow')
    # ### end Alembic commands ###
