"""added_more_filters_to_discovery

Revision ID: 36811bfbee6a
Revises: 4197c324d81d
Create Date: 2026-05-20 01:11:52.630732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36811bfbee6a'
down_revision: Union[str, None] = '4197c324d81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # min_bedrooms
    op.execute("""
        DO $$ BEGIN 
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='discovery_preferences' AND column_name='min_bedrooms') THEN
                ALTER TABLE discovery_preferences ADD COLUMN min_bedrooms INTEGER;
            END IF;
        END $$;
    """)
    # min_bathrooms
    op.execute("""
        DO $$ BEGIN 
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='discovery_preferences' AND column_name='min_bathrooms') THEN
                ALTER TABLE discovery_preferences ADD COLUMN min_bathrooms INTEGER;
            END IF;
        END $$;
    """)
    # min_square_feet
    op.execute("""
        DO $$ BEGIN 
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='discovery_preferences' AND column_name='min_square_feet') THEN
                ALTER TABLE discovery_preferences ADD COLUMN min_square_feet INTEGER;
            END IF;
        END $$;
    """)
    # min_price
    op.execute("""
        DO $$ BEGIN 
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='discovery_preferences' AND column_name='min_price') THEN
                ALTER TABLE discovery_preferences ADD COLUMN min_price FLOAT;
            END IF;
        END $$;
    """)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_preferences', 'min_price')
    op.drop_column('discovery_preferences', 'min_square_feet')
    op.drop_column('discovery_preferences', 'min_bathrooms')
    op.drop_column('discovery_preferences', 'min_bedrooms')
    # ### end Alembic commands ###
