"""added_more_filters_to_discovery

Revision ID: 36811bfbee6a
Revises: 4197c324d81d
Create Date: 2026-05-20 01:11:52.630732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36811bfbee6a'
down_revision: Union[str, None] = '4197c324d81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_preferences', sa.Column('min_bedrooms', sa.Integer(), nullable=True))
    op.add_column('discovery_preferences', sa.Column('min_bathrooms', sa.Integer(), nullable=True))
    op.add_column('discovery_preferences', sa.Column('min_square_feet', sa.Integer(), nullable=True))
    op.add_column('discovery_preferences', sa.Column('min_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_preferences', 'min_price')
    op.drop_column('discovery_preferences', 'min_square_feet')
    op.drop_column('discovery_preferences', 'min_bathrooms')
    op.drop_column('discovery_preferences', 'min_bedrooms')
    # ### end Alembic commands ###
