"""add_state_to_discovery

Revision ID: 4197c324d81d
Revises: 4af812d4210d
Create Date: 2026-05-19 23:12:31.373608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4197c324d81d'
down_revision: Union[str, None] = '4af812d4210d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_preferences', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_preferences', 'state')
    # ### end Alembic commands ###
