"""add_state_to_discovery

Revision ID: 4197c324d81d
Revises: 4af812d4210d
Create Date: 2026-05-19 23:12:31.373608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4197c324d81d'
down_revision: Union[str, None] = '4af812d4210d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='discovery_preferences' AND column_name='state') THEN
                ALTER TABLE discovery_preferences ADD COLUMN state VARCHAR;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_preferences', 'state')
    # ### end Alembic commands ###
