"""Merged property details in to the property column

Revision ID: 45cf816ad7f2
Revises: 61bdad42f358
Create Date: 2026-02-25 16:26:04.303853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45cf816ad7f2'
down_revision: Union[str, None] = '61bdad42f358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('property_details')
    op.alter_column('collections', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('collections', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('open_house_events', 'zipcode')
    op.drop_column('open_house_events', 'bedrooms')
    op.drop_column('open_house_events', 'state')
    op.drop_column('open_house_events', 'living_area')
    op.drop_column('open_house_events', 'home_status')
    op.drop_column('open_house_events', 'longitude')
    op.drop_column('open_house_events', 'city')
    op.drop_column('open_house_events', 'bathrooms')
    op.drop_column('open_house_events', 'price')
    op.drop_column('open_house_events', 'latitude')
    op.add_column('properties', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('list_agent_full_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('list_agent_email', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('list_office_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('list_office_phone', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('tax_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('open_house_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('architectural_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('construction_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('roof_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('foundation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('structure_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('interior_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('exterior_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('flooring', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('appliances', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('fireplaces', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('fireplace_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('door_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('window_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('cooling', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('heating', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('water_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('sewer', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('electric', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('utilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('garage_spaces', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('parking_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('has_garage', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('association_fee', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('association_fee_frequency', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('association_amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('association_fee_includes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('has_association', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('lot_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('topography', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('view', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('waterfront_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('has_waterfront_view', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('has_view', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('tax_annual_amount', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('tax_year', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('year_built', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('elementary_school', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('middle_or_junior_school', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('high_school', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('school_district_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('county', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('directions', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('cross_street', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('walk_score', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('zoning', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('direction_faces', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('tax_assessment_amount', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('land_assessment_amount', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('improvement_assessment_amount', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('assessment_year', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('capital_contribution_fee', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('possession', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('cooling_fuel', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('heating_fuel', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('lot_size_acres', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('attached_garage_yn', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('new_construction_yn', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('senior_community_yn', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('pets_allowed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('original_list_price', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('days_on_market', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('cumulative_days_on_market', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('standard_status', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('stories', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('stories_total', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('modification_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('properties', 'listing_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'home_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_properties_bathrooms'), 'properties', ['bathrooms'], unique=False)
    op.create_index(op.f('ix_properties_bedrooms'), 'properties', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index('ix_properties_city_state', 'properties', ['city', 'state'], unique=False)
    op.create_index(op.f('ix_properties_county'), 'properties', ['county'], unique=False)
    op.create_index(op.f('ix_properties_days_on_market'), 'properties', ['days_on_market'], unique=False)
    op.create_index(op.f('ix_properties_home_status'), 'properties', ['home_status'], unique=False)
    op.create_index(op.f('ix_properties_home_type'), 'properties', ['home_type'], unique=False)
    op.create_index('ix_properties_lat_long', 'properties', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_properties_latitude'), 'properties', ['latitude'], unique=False)
    op.create_index(op.f('ix_properties_living_area'), 'properties', ['living_area'], unique=False)
    op.create_index(op.f('ix_properties_longitude'), 'properties', ['longitude'], unique=False)
    op.create_index(op.f('ix_properties_modification_timestamp'), 'properties', ['modification_timestamp'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_school_district_name'), 'properties', ['school_district_name'], unique=False)
    op.create_index(op.f('ix_properties_standard_status'), 'properties', ['standard_status'], unique=False)
    op.create_index(op.f('ix_properties_state'), 'properties', ['state'], unique=False)
    op.create_index('ix_properties_status_price', 'properties', ['home_status', 'price'], unique=False)
    op.create_index(op.f('ix_properties_year_built'), 'properties', ['year_built'], unique=False)
    op.create_index(op.f('ix_properties_zipcode'), 'properties', ['zipcode'], unique=False)
    op.drop_column('properties', 'zestimate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('zestimate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_properties_zipcode'), table_name='properties')
    op.drop_index(op.f('ix_properties_year_built'), table_name='properties')
    op.drop_index('ix_properties_status_price', table_name='properties')
    op.drop_index(op.f('ix_properties_state'), table_name='properties')
    op.drop_index(op.f('ix_properties_standard_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_school_district_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_modification_timestamp'), table_name='properties')
    op.drop_index(op.f('ix_properties_longitude'), table_name='properties')
    op.drop_index(op.f('ix_properties_living_area'), table_name='properties')
    op.drop_index(op.f('ix_properties_latitude'), table_name='properties')
    op.drop_index('ix_properties_lat_long', table_name='properties')
    op.drop_index(op.f('ix_properties_home_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_home_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_days_on_market'), table_name='properties')
    op.drop_index(op.f('ix_properties_county'), table_name='properties')
    op.drop_index('ix_properties_city_state', table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_bedrooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_bathrooms'), table_name='properties')
    op.alter_column('properties', 'home_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('properties', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'listing_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('properties', 'modification_timestamp')
    op.drop_column('properties', 'stories_total')
    op.drop_column('properties', 'stories')
    op.drop_column('properties', 'standard_status')
    op.drop_column('properties', 'cumulative_days_on_market')
    op.drop_column('properties', 'days_on_market')
    op.drop_column('properties', 'original_list_price')
    op.drop_column('properties', 'pets_allowed')
    op.drop_column('properties', 'senior_community_yn')
    op.drop_column('properties', 'new_construction_yn')
    op.drop_column('properties', 'attached_garage_yn')
    op.drop_column('properties', 'lot_size_acres')
    op.drop_column('properties', 'heating_fuel')
    op.drop_column('properties', 'cooling_fuel')
    op.drop_column('properties', 'possession')
    op.drop_column('properties', 'capital_contribution_fee')
    op.drop_column('properties', 'assessment_year')
    op.drop_column('properties', 'improvement_assessment_amount')
    op.drop_column('properties', 'land_assessment_amount')
    op.drop_column('properties', 'tax_assessment_amount')
    op.drop_column('properties', 'direction_faces')
    op.drop_column('properties', 'zoning')
    op.drop_column('properties', 'walk_score')
    op.drop_column('properties', 'cross_street')
    op.drop_column('properties', 'directions')
    op.drop_column('properties', 'county')
    op.drop_column('properties', 'school_district_name')
    op.drop_column('properties', 'high_school')
    op.drop_column('properties', 'middle_or_junior_school')
    op.drop_column('properties', 'elementary_school')
    op.drop_column('properties', 'year_built')
    op.drop_column('properties', 'tax_year')
    op.drop_column('properties', 'tax_annual_amount')
    op.drop_column('properties', 'has_view')
    op.drop_column('properties', 'has_waterfront_view')
    op.drop_column('properties', 'waterfront_features')
    op.drop_column('properties', 'view')
    op.drop_column('properties', 'topography')
    op.drop_column('properties', 'lot_features')
    op.drop_column('properties', 'has_association')
    op.drop_column('properties', 'association_fee_includes')
    op.drop_column('properties', 'association_amenities')
    op.drop_column('properties', 'association_fee_frequency')
    op.drop_column('properties', 'association_fee')
    op.drop_column('properties', 'has_garage')
    op.drop_column('properties', 'parking_features')
    op.drop_column('properties', 'garage_spaces')
    op.drop_column('properties', 'utilities')
    op.drop_column('properties', 'electric')
    op.drop_column('properties', 'sewer')
    op.drop_column('properties', 'water_source')
    op.drop_column('properties', 'heating')
    op.drop_column('properties', 'cooling')
    op.drop_column('properties', 'window_features')
    op.drop_column('properties', 'door_features')
    op.drop_column('properties', 'fireplace_features')
    op.drop_column('properties', 'fireplaces')
    op.drop_column('properties', 'appliances')
    op.drop_column('properties', 'flooring')
    op.drop_column('properties', 'exterior_features')
    op.drop_column('properties', 'interior_features')
    op.drop_column('properties', 'levels')
    op.drop_column('properties', 'structure_type')
    op.drop_column('properties', 'foundation_details')
    op.drop_column('properties', 'roof_type')
    op.drop_column('properties', 'construction_materials')
    op.drop_column('properties', 'architectural_style')
    op.drop_column('properties', 'open_house_schedule')
    op.drop_column('properties', 'tax_history')
    op.drop_column('properties', 'price_history')
    op.drop_column('properties', 'list_office_phone')
    op.drop_column('properties', 'list_office_name')
    op.drop_column('properties', 'list_agent_email')
    op.drop_column('properties', 'list_agent_full_name')
    op.drop_column('properties', 'photos')
    op.drop_column('properties', 'description')
    op.add_column('open_house_events', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('bathrooms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('home_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('living_area', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('open_house_events', sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('collections', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('collections', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('property_details',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('list_agent_full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('list_agent_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('list_office_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('list_office_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tax_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('open_house_schedule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('architectural_style', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('construction_materials', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('roof_type', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('foundation_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('structure_type', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interior_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exterior_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('flooring', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('appliances', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fireplaces', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fireplace_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('door_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('window_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cooling', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('heating', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('water_source', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sewer', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('electric', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('utilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('garage_spaces', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('parking_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('has_garage', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('association_fee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('association_fee_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('association_amenities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('association_fee_includes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('has_association', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lot_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('topography', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('view', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('waterfront_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('has_waterfront_view', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_view', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tax_annual_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tax_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_built', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modification_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('elementary_school', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middle_or_junior_school', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('high_school', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('school_district_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('directions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cross_street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('walk_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zoning', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('direction_faces', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_assessment_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('land_assessment_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('improvement_assessment_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessment_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capital_contribution_fee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('possession', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cooling_fuel', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('heating_fuel', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('lot_size_acres', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('attached_garage_yn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('new_construction_yn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('senior_community_yn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pets_allowed', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('original_list_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('days_on_market', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cumulative_days_on_market', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('standard_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stories_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lot_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='property_details_property_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='property_details_pkey'),
    sa.UniqueConstraint('property_id', name='property_details_property_id_key')
    )
    op.drop_table('system_settings')
    # ### end Alembic commands ###
