"""add_unique_constraint_to_geographical_tables

Revision ID: 4af812d4210d
Revises: e86c19e7a94b
Create Date: 2026-05-16 03:48:19.273575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af812d4210d'
down_revision: Union[str, None] = 'e86c19e7a94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Brokerages
    op.execute("DROP INDEX IF EXISTS ix_brokerages_name")
    op.execute("CREATE INDEX IF NOT EXISTS ix_brokerages_name ON brokerages (name)")
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_brokerage_name_state') THEN
                ALTER TABLE brokerages ADD CONSTRAINT unique_brokerage_name_state UNIQUE (name, state);
            END IF;
        END $$;
    """)

    # Cities
    op.execute("DROP INDEX IF EXISTS ix_cities_name")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cities_name ON cities (name)")
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_city_name_state') THEN
                ALTER TABLE cities ADD CONSTRAINT unique_city_name_state UNIQUE (name, state);
            END IF;
        END $$;
    """)

    # School Districts
    op.execute("DROP INDEX IF EXISTS ix_school_districts_name")
    op.execute("CREATE INDEX IF NOT EXISTS ix_school_districts_name ON school_districts (name)")
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_school_district_name_state') THEN
                ALTER TABLE school_districts ADD CONSTRAINT unique_school_district_name_state UNIQUE (name, state);
            END IF;
        END $$;
    """)

    # Townships
    op.execute("DROP INDEX IF EXISTS ix_townships_name")
    op.execute("CREATE INDEX IF NOT EXISTS ix_townships_name ON townships (name)")
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_township_name_state') THEN
                ALTER TABLE townships ADD CONSTRAINT unique_township_name_state UNIQUE (name, state);
            END IF;
        END $$;
    """)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_township_name_state', 'townships', type_='unique')
    op.drop_index(op.f('ix_townships_name'), table_name='townships')
    op.create_index('ix_townships_name', 'townships', ['name'], unique=True)
    op.drop_constraint('unique_school_district_name_state', 'school_districts', type_='unique')
    op.drop_index(op.f('ix_school_districts_name'), table_name='school_districts')
    op.create_index('ix_school_districts_name', 'school_districts', ['name'], unique=True)
    op.drop_constraint('unique_city_name_state', 'cities', type_='unique')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.create_index('ix_cities_name', 'cities', ['name'], unique=True)
    op.drop_constraint('unique_brokerage_name_state', 'brokerages', type_='unique')
    op.drop_index(op.f('ix_brokerages_name'), table_name='brokerages')
    op.create_index('ix_brokerages_name', 'brokerages', ['name'], unique=True)
    # ### end Alembic commands ###
