"""Add PayPal subscription fields to users

Revision ID: 4d972b5c9240
Revises: 9c284f240dc1
Create Date: 2025-10-08 20:46:32.334405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d972b5c9240'
down_revision: Union[str, None] = '9c284f240dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed foreign key constraint changes as SQLite doesn't support them
    op.add_column('users', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_billing_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_billing_date')
    op.drop_column('users', 'subscription_started_at')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###
