"""Add last_synced_at to collections table

Revision ID: 513fb07021f0
Revises: e937c3f8e7ef
Create Date: 2025-11-28 15:22:48.996960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513fb07021f0'
down_revision: Union[str, None] = 'e937c3f8e7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Import TZDateTime from app.database
    from app.database import TZDateTime
    op.add_column('collections', sa.Column('last_synced_at', TZDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'last_synced_at')
    # ### end Alembic commands ###
