"""Initial Schema

Revision ID: 555a3b496371
Revises: 
Create Date: 2026-02-18 22:30:36.998493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '555a3b496371'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_key', sa.String(), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('zestimate', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('home_type', sa.String(), nullable=True),
    sa.Column('home_status', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('img_src', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_listing_key'), 'properties', ['listing_key'], unique=True)
    op.create_table('scheduled_emails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_emails_scheduled_for'), 'scheduled_emails', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_emails_status'), 'scheduled_emails', ['status'], unique=False)
    op.create_table('signup_verifications',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('brokerage', sa.String(), nullable=True),
    sa.Column('mls_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('plan_tier', sa.String(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_paypal_sync', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_subscription_id'), 'users', ['subscription_id'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_house_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('form_url', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('abbreviated_address', sa.String(), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('living_area', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('home_status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('similar_properties_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('property_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('list_agent_full_name', sa.String(), nullable=True),
    sa.Column('list_agent_email', sa.String(), nullable=True),
    sa.Column('list_office_name', sa.String(), nullable=True),
    sa.Column('list_office_phone', sa.String(), nullable=True),
    sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tax_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('open_house_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('architectural_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('construction_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roof_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('foundation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structure_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interior_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exterior_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flooring', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('appliances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fireplaces', sa.Integer(), nullable=True),
    sa.Column('fireplace_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('door_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('window_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cooling', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('heating', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('water_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sewer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('electric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('utilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('garage_spaces', sa.Float(), nullable=True),
    sa.Column('parking_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=True),
    sa.Column('association_fee', sa.Integer(), nullable=True),
    sa.Column('association_fee_frequency', sa.String(), nullable=True),
    sa.Column('association_amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('association_fee_includes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_association', sa.Boolean(), nullable=True),
    sa.Column('lot_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topography', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('view', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waterfront_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_waterfront_view', sa.Boolean(), nullable=True),
    sa.Column('has_view', sa.Boolean(), nullable=True),
    sa.Column('tax_annual_amount', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('modification_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elementary_school', sa.String(), nullable=True),
    sa.Column('middle_or_junior_school', sa.String(), nullable=True),
    sa.Column('high_school', sa.String(), nullable=True),
    sa.Column('school_district_name', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('cross_street', sa.String(), nullable=True),
    sa.Column('walk_score', sa.Integer(), nullable=True),
    sa.Column('zoning', sa.String(), nullable=True),
    sa.Column('direction_faces', sa.String(), nullable=True),
    sa.Column('tax_assessment_amount', sa.Integer(), nullable=True),
    sa.Column('land_assessment_amount', sa.Integer(), nullable=True),
    sa.Column('improvement_assessment_amount', sa.Integer(), nullable=True),
    sa.Column('assessment_year', sa.Integer(), nullable=True),
    sa.Column('capital_contribution_fee', sa.Integer(), nullable=True),
    sa.Column('possession', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cooling_fuel', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('heating_fuel', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lot_size_acres', sa.Float(), nullable=True),
    sa.Column('attached_garage_yn', sa.Boolean(), nullable=True),
    sa.Column('new_construction_yn', sa.Boolean(), nullable=True),
    sa.Column('senior_community_yn', sa.Boolean(), nullable=True),
    sa.Column('pets_allowed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_list_price', sa.Integer(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('cumulative_days_on_market', sa.Integer(), nullable=True),
    sa.Column('standard_status', sa.String(), nullable=True),
    sa.Column('stories', sa.Float(), nullable=True),
    sa.Column('stories_total', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('visitor_email', sa.String(), nullable=True),
    sa.Column('visitor_name', sa.String(), nullable=True),
    sa.Column('visitor_phone', sa.String(), nullable=True),
    sa.Column('original_open_house_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['original_open_house_event_id'], ['open_house_events.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('open_house_visitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('has_agent', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('open_house_event_id', sa.String(), nullable=True),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('form_url', sa.String(), nullable=True),
    sa.Column('interested_in_similar', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['open_house_event_id'], ['open_house_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('min_beds', sa.Integer(), nullable=True),
    sa.Column('max_beds', sa.Integer(), nullable=True),
    sa.Column('min_baths', sa.Float(), nullable=True),
    sa.Column('max_baths', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('min_year_built', sa.Integer(), nullable=True),
    sa.Column('max_year_built', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('cities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('townships', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('special_features', sa.Text(), nullable=True),
    sa.Column('is_town_house', sa.Boolean(), nullable=True),
    sa.Column('is_lot_land', sa.Boolean(), nullable=True),
    sa.Column('is_condo', sa.Boolean(), nullable=True),
    sa.Column('is_multi_family', sa.Boolean(), nullable=True),
    sa.Column('is_single_family', sa.Boolean(), nullable=True),
    sa.Column('is_apartment', sa.Boolean(), nullable=True),
    sa.Column('visiting_reason', sa.String(), nullable=True),
    sa.Column('has_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id')
    )
    op.create_table('collection_properties',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'property_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('property_address', sa.String(), nullable=True),
    sa.Column('visitor_name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_agent_id'), 'notifications', ['agent_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('property_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('visitor_name', sa.String(), nullable=True),
    sa.Column('visitor_email', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('disliked', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_tours',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('visitor_name', sa.String(), nullable=False),
    sa.Column('visitor_email', sa.String(), nullable=False),
    sa.Column('visitor_phone', sa.String(), nullable=False),
    sa.Column('preferred_date', sa.String(), nullable=False),
    sa.Column('preferred_time', sa.String(), nullable=False),
    sa.Column('preferred_date_2', sa.String(), nullable=True),
    sa.Column('preferred_time_2', sa.String(), nullable=True),
    sa.Column('preferred_date_3', sa.String(), nullable=True),
    sa.Column('preferred_time_3', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_tours')
    op.drop_table('property_interactions')
    op.drop_table('property_comments')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_agent_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('collection_properties')
    op.drop_table('collection_preferences')
    op.drop_table('open_house_visitors')
    op.drop_table('collections')
    op.drop_table('property_details')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('open_house_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('signup_verifications')
    op.drop_index(op.f('ix_scheduled_emails_status'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_scheduled_for'), table_name='scheduled_emails')
    op.drop_table('scheduled_emails')
    op.drop_index(op.f('ix_properties_listing_key'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('bundle_codes')
    # ### end Alembic commands ###
