"""Remove unused fields from properties table

Revision ID: 568b40e57bb4
Revises: 1e13849e2543
Create Date: 2025-08-30 15:12:45.451694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '568b40e57bb4'
down_revision: Union[str, None] = '1e13849e2543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'has_fireplace')
    op.drop_column('properties', 'tax_assessed_value')
    op.drop_column('properties', 'property_tax_rate')
    op.drop_column('properties', 'hoa_fee')
    op.drop_column('properties', 'price_change')
    op.drop_column('properties', 'date_price_changed')
    op.drop_column('properties', 'has_pool')
    op.drop_column('properties', 'zillow_data')
    op.drop_column('properties', 'has_garage')
    op.drop_column('properties', 'parking_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('parking_capacity', sa.INTEGER(), nullable=True))
    op.add_column('properties', sa.Column('has_garage', sa.BOOLEAN(), nullable=True))
    op.add_column('properties', sa.Column('zillow_data', sqlite.JSON(), nullable=True))
    op.add_column('properties', sa.Column('has_pool', sa.BOOLEAN(), nullable=True))
    op.add_column('properties', sa.Column('date_price_changed', sa.INTEGER(), nullable=True))
    op.add_column('properties', sa.Column('price_change', sa.INTEGER(), nullable=True))
    op.add_column('properties', sa.Column('hoa_fee', sa.FLOAT(), nullable=True))
    op.add_column('properties', sa.Column('property_tax_rate', sa.FLOAT(), nullable=True))
    op.add_column('properties', sa.Column('tax_assessed_value', sa.INTEGER(), nullable=True))
    op.add_column('properties', sa.Column('has_fireplace', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
