"""Add webhook_events table for idempotency

Revision ID: 582adc2044ae
Revises: bb14e8d4cffe
Create Date: 2025-11-11 01:32:29.774453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '582adc2044ae'
down_revision: Union[str, None] = 'bb14e8d4cffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', TZDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
