"""For lot size

Revision ID: 599bbd570d28
Revises: bcf7f8799d1f
Create Date: 2025-09-12 13:53:12.369046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599bbd570d28'
down_revision: Union[str, None] = 'bcf7f8799d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_house_events', sa.Column('lot_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_house_events', 'lot_size')
    # ### end Alembic commands ###
