"""Added price per square foot and raw township

Revision ID: 5accd1d3c095
Revises: 820029e93d16
Create Date: 2026-03-01 17:05:33.373761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5accd1d3c095'
down_revision: Union[str, None] = '820029e93d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('price_per_square_feet', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('mls_incorporated_city_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'mls_incorporated_city_name')
    op.drop_column('properties', 'price_per_square_feet')
    # ### end Alembic commands ###
