"""Added township

Revision ID: 5b709c76b381
Revises: e15dedcbcd5b
Create Date: 2026-02-27 23:46:49.198477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b709c76b381'
down_revision: Union[str, None] = 'e15dedcbcd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('township', sa.String(), nullable=True))
    op.create_index(op.f('ix_properties_township'), 'properties', ['township'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_township'), table_name='properties')
    op.drop_column('properties', 'township')
    # ### end Alembic commands ###
