"""Add PropertyTour table for tour scheduling

Revision ID: 60d986924168
Revises: fb9107c43d08
Create Date: 2025-10-02 17:01:45.732666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d986924168'
down_revision: Union[str, None] = 'fb9107c43d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_tours',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('visitor_name', sa.String(), nullable=False),
    sa.Column('visitor_email', sa.String(), nullable=False),
    sa.Column('visitor_phone', sa.String(), nullable=False),
    sa.Column('preferred_date', sa.String(), nullable=False),
    sa.Column('preferred_time', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Removed SQLite-incompatible constraint modifications
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_tours')
    # ### end Alembic commands ###
