"""add_broker_authorized_to_user

Revision ID: 61bdad42f358
Revises: 0f248eb7f0b7
Create Date: 2026-02-21 00:41:04.458347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bdad42f358'
down_revision: Union[str, None] = '0f248eb7f0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('broker_authorized', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'broker_authorized')
    # ### end Alembic commands ###
