"""visitor tracker

Revision ID: 635d0b21ac5b
Revises: c6668e8596b8
Create Date: 2026-03-11 16:27:50.971931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635d0b21ac5b'
down_revision: Union[str, None] = 'c6668e8596b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('last_visitor_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'last_visitor_activity_at')
    # ### end Alembic commands ###
