"""Updated the property

Revision ID: 67f2a66b8d85
Revises: 104aef2fe7d1
Create Date: 2025-09-01 23:58:54.735639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '67f2a66b8d85'
down_revision: Union[str, None] = '104aef2fe7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'lookup_address')
    op.drop_column('properties', 'last_synced')
    op.drop_column('properties', 'days_on_zillow')
    op.drop_column('properties', 'original_photos')
    op.drop_column('properties', 'year_built')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('year_built', sa.INTEGER(), nullable=True))
    op.add_column('properties', sa.Column('original_photos', sqlite.JSON(), nullable=True))
    op.add_column('properties', sa.Column('days_on_zillow', sa.INTEGER(), nullable=True))
    op.add_column('properties', sa.Column('last_synced', sa.DATETIME(), nullable=True))
    op.add_column('properties', sa.Column('lookup_address', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
