"""Added property details to cache

Revision ID: 6f6a3e4cff53
Revises: 7162af598f78
Create Date: 2025-09-06 17:44:24.459540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6f6a3e4cff53'
down_revision: Union[str, None] = '7162af598f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('detailed_property', sa.JSON(), nullable=True))
    op.drop_column('properties', 'detailed_properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('detailed_properties', sqlite.JSON(), nullable=True))
    op.drop_column('properties', 'detailed_property')
    # ### end Alembic commands ###
