"""Add property details caching fields

Revision ID: 7162af598f78
Revises: 67f2a66b8d85
Create Date: 2025-09-06 15:19:56.753353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7162af598f78'
down_revision: Union[str, None] = '67f2a66b8d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('detailed_properties', sa.JSON(), nullable=True))
    op.add_column('properties', sa.Column('detailed_data_cached', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('detailed_data_cached_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'detailed_data_cached_at')
    op.drop_column('properties', 'detailed_data_cached')
    op.drop_column('properties', 'detailed_properties')
    # ### end Alembic commands ###
