"""add notes to open house event and visitor

Revision ID: 74520f8dc278
Revises: 668f35f241f0
Create Date: 2026-01-24 22:29:15.357592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74520f8dc278'
down_revision: Union[str, None] = '668f35f241f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_house_events', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('open_house_visitors', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_house_visitors', 'notes')
    op.drop_column('open_house_events', 'notes')
    # ### end Alembic commands ###
