"""refactor_property_details

Revision ID: 7b17a9801021
Revises: af88ee91c940
Create Date: 2026-02-05 00:42:13.517911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import app.database

# revision identifiers, used by Alembic.
revision: str = '7b17a9801021'
down_revision: Union[str, None] = 'af88ee91c940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('list_agent_full_name', sa.String(), nullable=True),
    sa.Column('list_agent_email', sa.String(), nullable=True),
    sa.Column('list_office_name', sa.String(), nullable=True),
    sa.Column('list_office_phone', sa.String(), nullable=True),
    sa.Column('price_history', sa.JSON(), nullable=True),
    sa.Column('tax_history', sa.JSON(), nullable=True),
    sa.Column('open_house_schedule', sa.JSON(), nullable=True),
    sa.Column('architectural_style', sa.String(), nullable=True),
    sa.Column('construction_materials', sa.String(), nullable=True),
    sa.Column('roof_type', sa.String(), nullable=True),
    sa.Column('foundation_details', sa.String(), nullable=True),
    sa.Column('structure_type', sa.String(), nullable=True),
    sa.Column('levels', sa.String(), nullable=True),
    sa.Column('interior_features', sa.JSON(), nullable=True),
    sa.Column('exterior_features', sa.JSON(), nullable=True),
    sa.Column('flooring', sa.JSON(), nullable=True),
    sa.Column('appliances', sa.JSON(), nullable=True),
    sa.Column('fireplaces', sa.Integer(), nullable=True),
    sa.Column('fireplace_features', sa.JSON(), nullable=True),
    sa.Column('door_features', sa.JSON(), nullable=True),
    sa.Column('window_features', sa.JSON(), nullable=True),
    sa.Column('cooling', sa.JSON(), nullable=True),
    sa.Column('heating', sa.JSON(), nullable=True),
    sa.Column('water_source', sa.JSON(), nullable=True),
    sa.Column('sewer', sa.JSON(), nullable=True),
    sa.Column('electric', sa.JSON(), nullable=True),
    sa.Column('utilities', sa.JSON(), nullable=True),
    sa.Column('garage_spaces', sa.Float(), nullable=True),
    sa.Column('parking_features', sa.JSON(), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=True),
    sa.Column('association_fee', sa.Integer(), nullable=True),
    sa.Column('association_fee_frequency', sa.String(), nullable=True),
    sa.Column('association_amenities', sa.JSON(), nullable=True),
    sa.Column('association_fee_includes', sa.JSON(), nullable=True),
    sa.Column('has_association', sa.Boolean(), nullable=True),
    sa.Column('lot_features', sa.JSON(), nullable=True),
    sa.Column('topography', sa.String(), nullable=True),
    sa.Column('view', sa.JSON(), nullable=True),
    sa.Column('waterfront_features', sa.JSON(), nullable=True),
    sa.Column('has_waterfront_view', sa.Boolean(), nullable=True),
    sa.Column('has_view', sa.Boolean(), nullable=True),
    sa.Column('tax_annual_amount', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('modification_timestamp', app.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.TZDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', app.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.drop_table('reso_facts')
    op.drop_column('properties', 'detailed_data_cached_at')
    op.drop_column('properties', 'detailed_data_cached')
    op.drop_column('properties', 'detailed_property')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('detailed_property', sqlite.JSON(), nullable=True))
    op.add_column('properties', sa.Column('detailed_data_cached', sa.BOOLEAN(), nullable=True))
    op.add_column('properties', sa.Column('detailed_data_cached_at', sa.DATETIME(), nullable=True))
    op.create_table('reso_facts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('property_id', sa.VARCHAR(), nullable=False),
    sa.Column('architectural_style', sa.VARCHAR(), nullable=True),
    sa.Column('construction_materials', sa.VARCHAR(), nullable=True),
    sa.Column('roof_type', sa.VARCHAR(), nullable=True),
    sa.Column('foundation_details', sa.VARCHAR(), nullable=True),
    sa.Column('structure_type', sa.VARCHAR(), nullable=True),
    sa.Column('levels', sa.VARCHAR(), nullable=True),
    sa.Column('interior_features', sqlite.JSON(), nullable=True),
    sa.Column('exterior_features', sqlite.JSON(), nullable=True),
    sa.Column('flooring', sqlite.JSON(), nullable=True),
    sa.Column('appliances', sqlite.JSON(), nullable=True),
    sa.Column('fireplaces', sa.INTEGER(), nullable=True),
    sa.Column('fireplace_features', sqlite.JSON(), nullable=True),
    sa.Column('door_features', sqlite.JSON(), nullable=True),
    sa.Column('window_features', sqlite.JSON(), nullable=True),
    sa.Column('cooling', sqlite.JSON(), nullable=True),
    sa.Column('heating', sqlite.JSON(), nullable=True),
    sa.Column('water_source', sqlite.JSON(), nullable=True),
    sa.Column('sewer', sqlite.JSON(), nullable=True),
    sa.Column('electric', sqlite.JSON(), nullable=True),
    sa.Column('utilities', sqlite.JSON(), nullable=True),
    sa.Column('garage_spaces', sa.FLOAT(), nullable=True),
    sa.Column('parking_features', sqlite.JSON(), nullable=True),
    sa.Column('has_garage', sa.BOOLEAN(), nullable=True),
    sa.Column('association_fee', sa.INTEGER(), nullable=True),
    sa.Column('association_fee_frequency', sa.VARCHAR(), nullable=True),
    sa.Column('association_amenities', sqlite.JSON(), nullable=True),
    sa.Column('association_fee_includes', sqlite.JSON(), nullable=True),
    sa.Column('has_association', sa.BOOLEAN(), nullable=True),
    sa.Column('lot_features', sqlite.JSON(), nullable=True),
    sa.Column('topography', sa.VARCHAR(), nullable=True),
    sa.Column('view', sqlite.JSON(), nullable=True),
    sa.Column('waterfront_features', sqlite.JSON(), nullable=True),
    sa.Column('has_waterfront_view', sa.BOOLEAN(), nullable=True),
    sa.Column('has_view', sa.BOOLEAN(), nullable=True),
    sa.Column('tax_annual_amount', sa.INTEGER(), nullable=True),
    sa.Column('tax_year', sa.INTEGER(), nullable=True),
    sa.Column('year_built', sa.INTEGER(), nullable=True),
    sa.Column('modification_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.drop_table('property_details')
    # ### end Alembic commands ###
