"""Add unique constraint to subscription_id

Revision ID: 7b3f01fa8a3b
Revises: 582adc2044ae
Create Date: 2025-11-11 01:44:50.911073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3f01fa8a3b'
down_revision: Union[str, None] = '582adc2044ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_subscription_id'), 'users', ['subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscription_id'), table_name='users')
    # ### end Alembic commands ###
