"""Add cascade delete for collection dependencies

Revision ID: 7e209d2676fb
Revises: 599bbd570d28
Create Date: 2025-09-16 14:59:01.151672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e209d2676fb'
down_revision: Union[str, None] = '599bbd570d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLAlchemy ORM relationships with cascade="all, delete-orphan"
    # will handle deletion at the application level without needing database constraints
    # This migration is kept for reference but doesn't modify the database structure
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No database changes were made in upgrade, so no downgrade needed
    pass
    # ### end Alembic commands ###
