"""Add home type preferences to collection preferences

Revision ID: 81fe7115e3bf
Revises: 85d0a99953e3
Create Date: 2025-09-01 16:44:22.998413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fe7115e3bf'
down_revision: Union[str, None] = '85d0a99953e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_preferences', sa.Column('is_town_house', sa.Boolean(), nullable=True))
    op.add_column('collection_preferences', sa.Column('is_lot_land', sa.Boolean(), nullable=True))
    op.add_column('collection_preferences', sa.Column('is_condo', sa.Boolean(), nullable=True))
    op.add_column('collection_preferences', sa.Column('is_multi_family', sa.Boolean(), nullable=True))
    op.add_column('collection_preferences', sa.Column('is_single_family', sa.Boolean(), nullable=True))
    op.add_column('collection_preferences', sa.Column('is_apartment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_preferences', 'is_apartment')
    op.drop_column('collection_preferences', 'is_single_family')
    op.drop_column('collection_preferences', 'is_multi_family')
    op.drop_column('collection_preferences', 'is_condo')
    op.drop_column('collection_preferences', 'is_lot_land')
    op.drop_column('collection_preferences', 'is_town_house')
    # ### end Alembic commands ###
