"""added school districts

Revision ID: 820029e93d16
Revises: 5b709c76b381
Create Date: 2026-02-28 21:55:46.076340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '820029e93d16'
down_revision: Union[str, None] = '5b709c76b381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_districts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_districts_name'), 'school_districts', ['name'], unique=True)
    op.add_column('collection_preferences', sa.Column('school_districts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_preferences', 'school_districts')
    op.drop_index(op.f('ix_school_districts_name'), table_name='school_districts')
    op.drop_table('school_districts')
    # ### end Alembic commands ###
