"""Add server_default to PropertyInteraction updated_at column

Revision ID: 85d0a99953e3
Revises: e2494c0bbc3d
Create Date: 2025-08-31 17:07:58.869854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d0a99953e3'
down_revision: Union[str, None] = 'e2494c0bbc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
