"""make_user_fields_nullable

Revision ID: 882cdf38aafa
Revises: 11f9bc049246
Create Date: 2026-02-18 02:05:28.857038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882cdf38aafa'
down_revision: Union[str, None] = '11f9bc049246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'brokerage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'mls_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mls_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'brokerage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
