"""add visitor_name and visitor_email to property_comments

Revision ID: 8cb8e1b6e011
Revises: f3e2729415aa
Create Date: 2025-09-25 15:15:19.767011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb8e1b6e011'
down_revision: Union[str, None] = 'f3e2729415aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add columns, skip constraint modifications for SQLite compatibility
    op.add_column('property_comments', sa.Column('visitor_name', sa.String(), nullable=True))
    op.add_column('property_comments', sa.Column('visitor_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop columns, skip constraint modifications for SQLite compatibility
    op.drop_column('property_comments', 'visitor_email')
    op.drop_column('property_comments', 'visitor_name')
    # ### end Alembic commands ###
