"""cleaned up unused property fields

Revision ID: 8f83a95582f5
Revises: 45cf816ad7f2
Create Date: 2026-02-25 23:42:29.957912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f83a95582f5'
down_revision: Union[str, None] = '45cf816ad7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('mls_list_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('price_change_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('subdivision_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('listing_tax_id', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('above_grade_finished_area', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('below_grade_finished_area', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('basement', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('accessibility_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('has_basement', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('has_central_air', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('has_fireplace', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('association_fee_2', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('association_fee_2_frequency', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('list_agent_preferred_phone', sa.String(), nullable=True))
    op.drop_index('ix_properties_standard_status', table_name='properties')
    op.create_index(op.f('ix_properties_subdivision_name'), 'properties', ['subdivision_name'], unique=False)
    op.drop_column('properties', 'price_history')
    op.drop_column('properties', 'stories_total')
    op.drop_column('properties', 'improvement_assessment_amount')
    op.drop_column('properties', 'tax_history')
    op.drop_column('properties', 'open_house_schedule')
    op.drop_column('properties', 'electric')
    op.drop_column('properties', 'standard_status')
    op.drop_column('properties', 'cross_street')
    op.drop_column('properties', 'topography')
    op.drop_column('properties', 'land_assessment_amount')
    op.drop_column('properties', 'country')
    op.drop_column('properties', 'walk_score')
    op.drop_column('properties', 'direction_faces')
    op.drop_column('properties', 'capital_contribution_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('capital_contribution_fee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('direction_faces', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('walk_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('land_assessment_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('topography', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('cross_street', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('standard_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('electric', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('open_house_schedule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('tax_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('improvement_assessment_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('stories_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_properties_subdivision_name'), table_name='properties')
    op.create_index('ix_properties_standard_status', 'properties', ['standard_status'], unique=False)
    op.drop_column('properties', 'list_agent_preferred_phone')
    op.drop_column('properties', 'association_fee_2_frequency')
    op.drop_column('properties', 'association_fee_2')
    op.drop_column('properties', 'has_fireplace')
    op.drop_column('properties', 'has_central_air')
    op.drop_column('properties', 'has_basement')
    op.drop_column('properties', 'accessibility_features')
    op.drop_column('properties', 'basement')
    op.drop_column('properties', 'below_grade_finished_area')
    op.drop_column('properties', 'above_grade_finished_area')
    op.drop_column('properties', 'listing_tax_id')
    op.drop_column('properties', 'subdivision_name')
    op.drop_column('properties', 'price_change_timestamp')
    op.drop_column('properties', 'mls_list_date')
    # ### end Alembic commands ###
