"""Add additional preferred date/time slots to PropertyTour

Revision ID: 9c284f240dc1
Revises: 60d986924168
Create Date: 2025-10-02 17:38:32.554850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c284f240dc1'
down_revision: Union[str, None] = '60d986924168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed SQLite-incompatible constraint modifications
    op.add_column('property_tours', sa.Column('preferred_date_2', sa.String(), nullable=True))
    op.add_column('property_tours', sa.Column('preferred_time_2', sa.String(), nullable=True))
    op.add_column('property_tours', sa.Column('preferred_date_3', sa.String(), nullable=True))
    op.add_column('property_tours', sa.Column('preferred_time_3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_tours', 'preferred_time_3')
    op.drop_column('property_tours', 'preferred_date_3')
    op.drop_column('property_tours', 'preferred_time_2')
    op.drop_column('property_tours', 'preferred_date_2')
    # ### end Alembic commands ###
