"""added unparsed_address

Revision ID: a88e28187f03
Revises: 8f83a95582f5
Create Date: 2026-02-25 23:58:47.095822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88e28187f03'
down_revision: Union[str, None] = '8f83a95582f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('unparsed_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'unparsed_address')
    # ### end Alembic commands ###
