"""Add state and brokerage to User model

Revision ID: acede06d2022
Revises: 9d7f0f2362be
Create Date: 2025-08-24 20:22:27.384683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acede06d2022'
down_revision: Union[str, None] = '9d7f0f2362be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('brokerage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'brokerage')
    op.drop_column('users', 'state')
    # ### end Alembic commands ###
