"""remove days_on_zillow column

Revision ID: af3e07e53e9a
Revises: 3158e8c609d8
Create Date: 2025-11-16 05:56:20.293189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3e07e53e9a'
down_revision: Union[str, None] = '3158e8c609d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'days_on_zillow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('days_on_zillow', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
