"""add mls_id to users

Revision ID: af88ee91c940
Revises: 657e19d2cca8
Create Date: 2026-02-03 23:37:48.945192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af88ee91c940'
down_revision: Union[str, None] = '657e19d2cca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mls_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mls_id')
    # ### end Alembic commands ###
