"""Add next_billing_date and last_paypal_sync to users

Revision ID: b86c7aa8a61c
Revises: 02b055d0e3e2
Create Date: 2025-10-12 02:54:33.149317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86c7aa8a61c'
down_revision: Union[str, None] = '02b055d0e3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip foreign key changes (SQLite doesn't support ALTER constraint)
    # op.drop_constraint(None, 'collection_preferences', type_='foreignkey')
    # op.create_foreign_key(None, 'collection_preferences', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    # op.drop_constraint(None, 'property_comments', type_='foreignkey')
    # op.create_foreign_key(None, 'property_comments', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    # op.drop_constraint(None, 'property_interactions', type_='foreignkey')
    # op.create_foreign_key(None, 'property_interactions', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')

    # Add new columns only
    op.add_column('users', sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_paypal_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_paypal_sync')
    op.drop_column('users', 'next_billing_date')
    # Skip foreign key changes (SQLite doesn't support ALTER constraint)
    # op.drop_constraint(None, 'property_interactions', type_='foreignkey')
    # op.create_foreign_key(None, 'property_interactions', 'collections', ['collection_id'], ['id'])
    # op.drop_constraint(None, 'property_comments', type_='foreignkey')
    # op.create_foreign_key(None, 'property_comments', 'collections', ['collection_id'], ['id'])
    # op.drop_constraint(None, 'collection_preferences', type_='foreignkey')
    # op.create_foreign_key(None, 'collection_preferences', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###
