"""Add pending_plan_change to users

Revision ID: bb14e8d4cffe
Revises: 7fccaa4003de
Create Date: 2025-11-09 03:08:13.769397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb14e8d4cffe'
down_revision: Union[str, None] = '7fccaa4003de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite note: Skipping constraint modifications as they require table recreation
    # The ondelete='CASCADE' is already defined in the model and will apply to new tables
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite note: Nothing to downgrade as upgrade was skipped
    pass
    # ### end Alembic commands ###
