"""Add cities and
  townships JSON arrays

Revision ID: bcf7f8799d1f
Revises: 2d6c5473567d
Create Date: 2025-09-12 01:54:48.344757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf7f8799d1f'
down_revision: Union[str, None] = '2d6c5473567d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
