"""Add collection notification toggles

Revision ID: bea6a6e83a5e
Revises: 2eed9048440b
Create Date: 2026-03-12 20:28:33.051053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea6a6e83a5e'
down_revision: Union[str, None] = '2eed9048440b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('notify_visitor', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('collections', sa.Column('notify_agent', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'notify_agent')
    op.drop_column('collections', 'notify_visitor')
    # ### end Alembic commands ###
