"""added share token

Revision ID: bf0c200e1de9
Revises: f17803cd826c
Create Date: 2025-08-24 16:15:02.629641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0c200e1de9'
down_revision: Union[str, None] = 'f17803cd826c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_notes')
    op.drop_table('open_house_sign_ins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_house_sign_ins',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('visitor_name', sa.VARCHAR(), nullable=False),
    sa.Column('visitor_email', sa.VARCHAR(), nullable=True),
    sa.Column('visitor_phone', sa.VARCHAR(), nullable=True),
    sa.Column('signed_in_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['open_house_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_notes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('property_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
