"""add last_agent_dismissed_at to collection

Revision ID: c8835a9a07fc
Revises: fed296ab93aa
Create Date: 2026-04-26 19:58:06.016723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8835a9a07fc'
down_revision: Union[str, None] = 'fed296ab93aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('last_agent_dismissed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'last_agent_dismissed_at')
    # ### end Alembic commands ###
