"""Added more to preferences

Revision ID: e15dedcbcd5b
Revises: ddd181c27ce9
Create Date: 2026-02-27 22:43:33.823121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15dedcbcd5b'
down_revision: Union[str, None] = 'ddd181c27ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_preferences', sa.Column('is_commercial', sa.Boolean(), nullable=True))
    op.add_column('collection_preferences', sa.Column('is_farm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_preferences', 'is_farm')
    op.drop_column('collection_preferences', 'is_commercial')
    # ### end Alembic commands ###
