"""Add property details to open_house_events table

Revision ID: e2494c0bbc3d
Revises: 568b40e57bb4
Create Date: 2025-08-30 19:42:59.890509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2494c0bbc3d'
down_revision: Union[str, None] = '568b40e57bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_house_events', sa.Column('bedrooms', sa.Integer(), nullable=True))
    op.add_column('open_house_events', sa.Column('bathrooms', sa.Float(), nullable=True))
    op.add_column('open_house_events', sa.Column('living_area', sa.Integer(), nullable=True))
    op.add_column('open_house_events', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_house_events', 'price')
    op.drop_column('open_house_events', 'living_area')
    op.drop_column('open_house_events', 'bathrooms')
    op.drop_column('open_house_events', 'bedrooms')
    # ### end Alembic commands ###
