"""index_list_office_name

Revision ID: e86c19e7a94b
Revises: f7550c49d458
Create Date: 2026-05-14 18:17:54.786924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86c19e7a94b'
down_revision: Union[str, None] = 'f7550c49d458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use idempotent drop to avoid failure if already dropped
    op.execute("DROP INDEX IF EXISTS idx_properties_full_address_trgm")
    
    # Create indices if they don't exist
    op.execute("CREATE INDEX IF NOT EXISTS ix_properties_full_address ON properties (full_address)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_properties_list_office_name ON properties (list_office_name)")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_list_office_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_full_address'), table_name='properties')
    op.create_index('idx_properties_full_address_trgm', 'properties', ['full_address'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
