"""index_list_office_name

Revision ID: e86c19e7a94b
Revises: f7550c49d458
Create Date: 2026-05-14 18:17:54.786924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86c19e7a94b'
down_revision: Union[str, None] = 'f7550c49d458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_properties_full_address_trgm', table_name='properties', postgresql_using='gin')
    op.create_index(op.f('ix_properties_full_address'), 'properties', ['full_address'], unique=False)
    op.create_index(op.f('ix_properties_list_office_name'), 'properties', ['list_office_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_list_office_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_full_address'), table_name='properties')
    op.create_index('idx_properties_full_address_trgm', 'properties', ['full_address'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
