"""restored open house event snapshot fields

Revision ID: f3107b8e095c
Revises: 9c13da2c00f5
Create Date: 2026-02-26 01:49:30.535149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3107b8e095c'
down_revision: Union[str, None] = '9c13da2c00f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_house_events', sa.Column('city', sa.String(), nullable=True))
    op.add_column('open_house_events', sa.Column('state', sa.String(), nullable=True))
    op.add_column('open_house_events', sa.Column('zipcode', sa.String(), nullable=True))
    op.add_column('open_house_events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('open_house_events', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('open_house_events', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('open_house_events', sa.Column('bedrooms', sa.Float(), nullable=True))
    op.add_column('open_house_events', sa.Column('bathrooms', sa.Float(), nullable=True))
    op.add_column('open_house_events', sa.Column('living_area', sa.Integer(), nullable=True))
    op.add_column('open_house_events', sa.Column('home_status', sa.String(), nullable=True))
    op.add_column('open_house_events', sa.Column('listing_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_house_events', 'listing_key')
    op.drop_column('open_house_events', 'home_status')
    op.drop_column('open_house_events', 'living_area')
    op.drop_column('open_house_events', 'bathrooms')
    op.drop_column('open_house_events', 'bedrooms')
    op.drop_column('open_house_events', 'price')
    op.drop_column('open_house_events', 'longitude')
    op.drop_column('open_house_events', 'latitude')
    op.drop_column('open_house_events', 'zipcode')
    op.drop_column('open_house_events', 'state')
    op.drop_column('open_house_events', 'city')
    # ### end Alembic commands ###
