"""Add soft delete to open house events

Revision ID: f3e2729415aa
Revises: 2231c0fc186f
Create Date: 2025-09-16 21:25:27.467002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e2729415aa'
down_revision: Union[str, None] = '2231c0fc186f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add soft delete columns to open_house_events
    op.add_column('open_house_events', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('open_house_events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # Set default values for existing records
    op.execute("UPDATE open_house_events SET is_deleted = 0 WHERE is_deleted IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove soft delete columns from open_house_events
    op.drop_column('open_house_events', 'deleted_at')
    op.drop_column('open_house_events', 'is_deleted')
    # ### end Alembic commands ###
