"""add_similar_property_ids_to_open_house

Revision ID: f5ad41bcfca9
Revises: 6c8d36288708
Create Date: 2026-02-13 17:50:46.981689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ad41bcfca9'
down_revision: Union[str, None] = '6c8d36288708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_house_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_property_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_house_events', schema=None) as batch_op:
        batch_op.drop_column('similar_property_ids')

    # ### end Alembic commands ###
