"""add_parent_name_to_brokerage

Revision ID: f7550c49d458
Revises: 27e3940dfd06
Create Date: 2026-05-13 19:07:18.421257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7550c49d458'
down_revision: Union[str, None] = '27e3940dfd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brokerages', sa.Column('parent_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_brokerages_parent_name'), 'brokerages', ['parent_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brokerages_parent_name'), table_name='brokerages')
    op.drop_column('brokerages', 'parent_name')
    # ### end Alembic commands ###
