"""add_parent_name_to_brokerage

Revision ID: f7550c49d458
Revises: 27e3940dfd06
Create Date: 2026-05-13 19:07:18.421257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7550c49d458'
down_revision: Union[str, None] = '27e3940dfd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='brokerages' AND column_name='parent_name') THEN
                ALTER TABLE brokerages ADD COLUMN parent_name VARCHAR;
            END IF;
        END $$;
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_brokerages_parent_name ON brokerages (parent_name)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brokerages_parent_name'), table_name='brokerages')
    op.drop_column('brokerages', 'parent_name')
    # ### end Alembic commands ###
