"""Add address, city, and township fields to CollectionPreferences

Revision ID: fbd80bcbd06d
Revises: 6f6a3e4cff53
Create Date: 2025-09-11 14:34:15.074694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd80bcbd06d'
down_revision: Union[str, None] = '6f6a3e4cff53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_preferences', sa.Column('address', sa.String(), nullable=True))
    op.add_column('collection_preferences', sa.Column('city', sa.String(), nullable=True))
    op.add_column('collection_preferences', sa.Column('township', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_preferences', 'township')
    op.drop_column('collection_preferences', 'city')
    op.drop_column('collection_preferences', 'address')
    # ### end Alembic commands ###
