"""Add visitor form fields to preferences and remove additional_comments

Revision ID: fcf867c65956
Revises: 71ed0cfbcd66
Create Date: 2025-08-25 02:12:58.077226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf867c65956'
down_revision: Union[str, None] = '71ed0cfbcd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_preferences', sa.Column('timeframe', sa.String(), nullable=True))
    op.add_column('collection_preferences', sa.Column('visiting_reason', sa.String(), nullable=True))
    op.add_column('collection_preferences', sa.Column('has_agent', sa.String(), nullable=True))
    op.drop_column('open_house_visitors', 'additional_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_house_visitors', sa.Column('additional_comments', sa.TEXT(), nullable=True))
    op.drop_column('collection_preferences', 'has_agent')
    op.drop_column('collection_preferences', 'visiting_reason')
    op.drop_column('collection_preferences', 'timeframe')
    # ### end Alembic commands ###
